# -*- coding: utf-8 -*-
"""YOLO_V10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LP9iW1A712XBXx2mG7YWyQ8DcSfZewhK
"""

!pip install supervison

!pip install -q git+https://github.com/THU-MIG/yolov10.git

!chdir /content/drive/MyDrive/YOLO_V10

!mkdir /content/drive/MyDrive/YOLO_V10/weights
!wget -P /content/drive/MyDrive/YOLO_V10/weights -q https://github.com/jameslahm/yolov10/releases/download/v1.0/yolov10n.pt
!wget -P /content/drive/MyDrive/YOLO_V10/weights -q https://github.com/jameslahm/yolov10/releases/download/v1.0/yolov10s.pt
!wget -P /content/drive/MyDrive/YOLO_V10/weights -q https://github.com/jameslahm/yolov10/releases/download/v1.0/yolov10m.pt
!wget -P /content/drive/MyDrive/YOLO_V10/weights -q https://github.com/jameslahm/yolov10/releases/download/v1.0/yolov10b.pt
!wget -P /content/drive/MyDrive/YOLO_V10/weights -q https://github.com/jameslahm/yolov10/releases/download/v1.0/yolov10x.pt
!wget -P /content/drive/MyDrive/YOLO_V10/weights -q https://github.com/jameslahm/yolov10/releases/download/v1.0/yolov10l.pt
!ls -lh /content/drive/MyDrive/YOLO_V10/weights

#!yolo task=detect mode=predict conf=0.25 save=True model=/content/drive/MyDrive/YOLO_V10/weights/yolov10n source=/content/drive/MyDrive/YOLO_V10/download.jpg save=True

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="WCkhryaEvEA4f8Zo1PTT")
project = rf.workspace("roboflow-jvuqo").project("football-players-detection-3zvbc")
version = project.version(9)
dataset = version.download("yolov8")

!yolo task=detect mode=train data=/content/drive/MyDrive/YOLO_V10/football-players-detection-9/data.yaml model=/content/drive/MyDrive/YOLO_V10/weights/yolov10n.pt epochs=50 batch=8

'''import torch
from your_model_file import YourModel  # Replace with your actual model import

# Load your ONNX or TensorRT model
onnx_model = torch.onnx.load('/content/drive/MyDrive/YOLO_V10/weights/yolov10m')

# Convert it to PyTorch format
torch.save(onnx_model, '/content/drive/MyDrive/YOLO_V10/weights/yolov10m.pt')'''

'''from ultralytics import YOLOv10

#model = YOLOv10()
# If you want to finetune the model with pretrained weights, you could load the
# pretrained weights like below
# model = YOLOv10.from_pretrained('jameslahm/yolov10{n/s/m/b/l/x}')
# or
!wget https://github.com/THU-MIG/yolov10/releases/download/v1.1/yolov10{n/s/m/b/l/x}.pt
model = YOLOv10('/content/drive/MyDrive/YOLO_V10/weights/yolov10m')

model.train(data='/content/drive/MyDrive/YOLO_V10/football-players-detection-9/data.yaml', epochs=50, batch=256, imgsz=640)